/* Generated By:JJTree&JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROCEDURE = 5;
  /** RegularExpression Id. */
  int BEGIN = 6;
  /** RegularExpression Id. */
  int INTEGER = 7;
  /** RegularExpression Id. */
  int FOR = 8;
  /** RegularExpression Id. */
  int UNTIL = 9;
  /** RegularExpression Id. */
  int DO = 10;
  /** RegularExpression Id. */
  int OD = 11;
  /** RegularExpression Id. */
  int IF = 12;
  /** RegularExpression Id. */
  int THEN = 13;
  /** RegularExpression Id. */
  int ELSE = 14;
  /** RegularExpression Id. */
  int FI = 15;
  /** RegularExpression Id. */
  int END = 16;
  /** RegularExpression Id. */
  int NUMERAL = 17;
  /** RegularExpression Id. */
  int ASSIGN = 18;
  /** RegularExpression Id. */
  int MUL = 19;
  /** RegularExpression Id. */
  int ADD = 20;
  /** RegularExpression Id. */
  int SUB = 21;
  /** RegularExpression Id. */
  int DIV = 22;
  /** RegularExpression Id. */
  int GTE = 23;
  /** RegularExpression Id. */
  int LTE = 24;
  /** RegularExpression Id. */
  int LT = 25;
  /** RegularExpression Id. */
  int GT = 26;
  /** RegularExpression Id. */
  int EQ = 27;
  /** RegularExpression Id. */
  int NEQ = 28;
  /** RegularExpression Id. */
  int LPAR = 29;
  /** RegularExpression Id. */
  int RPAR = 30;
  /** RegularExpression Id. */
  int SEMI = 31;
  /** RegularExpression Id. */
  int COMMA = 32;
  /** RegularExpression Id. */
  int ID = 33;
  /** RegularExpression Id. */
  int ERROR = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"procedure\"",
    "\"begin\"",
    "\"integer\"",
    "\"for\"",
    "\"until\"",
    "\"do\"",
    "\"od\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"fi\"",
    "\"end\"",
    "<NUMERAL>",
    "\"=\"",
    "\"*\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\">=\"",
    "\"<=\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\"!=\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
    "<ID>",
    "<ERROR>",
  };

}
