/* Generated By:JavaCC: Do not edit this line. ParserVisitor.java Version 5.0 */
package parser;

public interface ParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(Start node, Object data);
  public Object visit(Procedure node, Object data);
  public Object visit(List node, Object data);
  public Object visit(ExprStmt node, Object data);
  public Object visit(IfStmt node, Object data);
  public Object visit(ForStmt node, Object data);
  public Object visit(Param node, Object data);
  public Object visit(IdDecl node, Object data);
  public Object visit(Opt node, Object data);
  public Object visit(Assgn node, Object data);
  public Object visit(Lt node, Object data);
  public Object visit(Gt node, Object data);
  public Object visit(Gte node, Object data);
  public Object visit(Lte node, Object data);
  public Object visit(Eq node, Object data);
  public Object visit(Neq node, Object data);
  public Object visit(Add node, Object data);
  public Object visit(Sub node, Object data);
  public Object visit(Mul node, Object data);
  public Object visit(Div node, Object data);
  public Object visit(FuncCall node, Object data);
  public Object visit(Numeral node, Object data);
  public Object visit(IdUse node, Object data);
  public Object visit(Id node, Object data);
  public Object visit(Type node, Object data);
}
/* JavaCC - OriginalChecksum=5b821ce71152cad8082e0aec2ee13248 (do not edit this line) */
