/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
package parser;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROCEDURE = 1;
  public int JJTVOID = 2;
  public int JJTLIST = 3;
  public int JJTEXPRSTMT = 4;
  public int JJTIFSTMT = 5;
  public int JJTFORSTMT = 6;
  public int JJTPARAM = 7;
  public int JJTIDDECL = 8;
  public int JJTOPT = 9;
  public int JJTASSGN = 10;
  public int JJTLT = 11;
  public int JJTGT = 12;
  public int JJTGTE = 13;
  public int JJTLTE = 14;
  public int JJTEQ = 15;
  public int JJTNEQ = 16;
  public int JJTADD = 17;
  public int JJTSUB = 18;
  public int JJTMUL = 19;
  public int JJTDIV = 20;
  public int JJTFUNCCALL = 21;
  public int JJTNUMERAL = 22;
  public int JJTIDUSE = 23;
  public int JJTID = 24;
  public int JJTTYPE = 25;


  public String[] jjtNodeName = {
    "Start",
    "Procedure",
    "void",
    "List",
    "ExprStmt",
    "IfStmt",
    "ForStmt",
    "Param",
    "IdDecl",
    "Opt",
    "Assgn",
    "Lt",
    "Gt",
    "Gte",
    "Lte",
    "Eq",
    "Neq",
    "Add",
    "Sub",
    "Mul",
    "Div",
    "FuncCall",
    "Numeral",
    "IdUse",
    "Id",
    "Type",
  };
}
/* JavaCC - OriginalChecksum=aad38ef4339bb3c0a8a32b2062a5c6ea (do not edit this line) */
